name: 💡 Feature request
description: Suggest an idea, an improvement, or a new bug "species".
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem or idea?
      description: What are you trying to do? What's missing today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
